# Generated by Django 2.0.7 on 2019-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_salaryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='salary_date',
            field=models.DateField(auto_now_add=True, default='2019-04-21'),
            preserve_default=False,
        ),
    ]
