# Generated by Django 2.0.7 on 2019-04-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_salaryrecord_salary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='leaves',
            field=models.IntegerField(default=27),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='working_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
